spring:
  application:
    name: flooding-server-v2

sdk:
  logging:
    enabled: true
    not-logging-urls:
      - "/v3/api-docs/**"
      - "/swagger-ui/**"

  response:
    enabled: true
    not-wrapping-urls:
      - "/v3/api-docs/**"
      - "/v3/api-docs"
      - "/swagger-ui/**"

  swagger:
    enabled: true
    title: "Flooding Server API"
    version: "v2"
    paths-to-match:
      - "/**"

  exception:
    enabled: true
    use-english-message: false

oauth:
  client-id: ${OAUTH_CLIENT_ID}
  client-secret: ${OAUTH_CLIENT_SECRET}

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: 3600000
  refresh-token-expiration: 604800000
